### ISSUE TITLE
No realsense2 package which is compatibile with 2.24.0

### ISSUE THREAD

**Issue by wikpunGitHub** [JetsonHacksNano/installRealSenseROS#2]
Hi, I ran the script and got the below error message. Does anyone have any idea how to solve it?

I switched from LattePanda and Udoo X86 to Nano for my robotics project due to openCV operation performance issue. I desperately want to get it working on Nano. Thanks!

```
CMake Warning at realsense-ros/realsense2_camera/CMakeLists.txt:37 (find_package):
  Could not find a configuration file for package "realsense2" that is
  compatible with requested version "2.24.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/realsense2/realsense2Config.cmake, version: 2.22.0
CMake Error at realsense-ros/realsense2_camera/CMakeLists.txt:39 (message):
  
   Intel RealSense SDK 2.0 is missing, please install it from https://github.com/IntelRealSense/librealsense/releases

```

**Comment by JetsonHacksNano** [comment]
You must install matching version of librealsense and realsense-ros. These should correspond to your L4T/JetPack installation (see releases). As of this writing, the latest installers are for L4T 32.2.1/JetPack 4.2.2, librealsense 2.25.0 and realsense-ros 2.28.0. If you have a different version of L4T, please check the releases to match.

**Comment by FrankGaoX** [comment]
For the latest Jetpack4.4, is there a matching requirement?
